// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADq1618EG2Kq7Kj5wN8t1hE_KYPqMuXJs',
    appId: '1:248083068955:web:6c28e6524d4c99e1d3e0be',
    messagingSenderId: '248083068955',
    projectId: 'medi-spot',
    authDomain: 'medi-spot.firebaseapp.com',
    storageBucket: 'medi-spot.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUBSn1G7bLccNZZwYjtVhGKA7DAT_ibBs',
    appId: '1:248083068955:android:241aff67fd5a14d4d3e0be',
    messagingSenderId: '248083068955',
    projectId: 'medi-spot',
    storageBucket: 'medi-spot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0lXBKUNFokSLoFxAYmW46LR4_m0cir58',
    appId: '1:248083068955:ios:ce9a24d440896e3ed3e0be',
    messagingSenderId: '248083068955',
    projectId: 'medi-spot',
    storageBucket: 'medi-spot.firebasestorage.app',
    iosBundleId: 'com.example.medispot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0lXBKUNFokSLoFxAYmW46LR4_m0cir58',
    appId: '1:248083068955:ios:ce9a24d440896e3ed3e0be',
    messagingSenderId: '248083068955',
    projectId: 'medi-spot',
    storageBucket: 'medi-spot.firebasestorage.app',
    iosBundleId: 'com.example.medispot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADq1618EG2Kq7Kj5wN8t1hE_KYPqMuXJs',
    appId: '1:248083068955:web:287ab969721cdd70d3e0be',
    messagingSenderId: '248083068955',
    projectId: 'medi-spot',
    authDomain: 'medi-spot.firebaseapp.com',
    storageBucket: 'medi-spot.firebasestorage.app',
  );
}
